### ISSUE TITLE
Add the "Keep above" button

### ISSUE THREAD

**Issue by maverick74** [antroids/application-title-bar#10]
Please add the "Keep Above" button

(others could also be handy to some, but to me the "keep above" is crucial)

Everything else is working great!!! Thank you for this!!!

**Comment by antroids** [comment]
Implemented in 0.2.6.
The button can be added in Appearance settings.

**Comment by maverick74** [comment]
**Thank you so much for this fix!!!**

Now that this is archived and it won't spam too much, let me ask @antroids an honest off-topic question:

Any plans to provide a Global Menu alternative?

Plasma's default Global Menu have a > [problem](https://bugs.kde.org/show_bug.cgi?id=435928) < that, while it's probably a very easy fix, keeps me from using it... So, i'm curios if you have anything like it planned...

**Comment by maverick74** [comment]
hum... i'm trying the 0.2.6 version and while the buttons appear on the config dialog, they do not appear on the plasmoid itself after i apply the changes...

can you replicate it?

**Comment by antroids** [comment]
Are there any errors in logs?
`journalctl --user --unit=plasma-plasmashell --grep=application-title-bar`

**Comment by maverick74** [comment]
OK, from the journal it was reporting 0.2.3 (while the config page reported 0.2.6)

But when i updated it had a weird behavior (i pressed update on the GNHS but nothing happened... i had to enter the plasmoid and press update again)...

So, based on this, i removed the plasmoid, rebooted, and reinstalled it again.

Now it's working just fine :)

(except for the part that the "Keep Above" button does not get hided if we set  the "**Show disabled elements**" to "_hide_" or "_hide, keep space_"... but for that i think i should fill another bug report...)

**Comment by maverick74** [comment]
> I'm on Kde Neon and also have issues with widgets installation. It seems they also not implemented version dialog, so I removed all older versions from the store.

Yeah, neon here too!
I noticed the versions dialog was buggy as well!

About https://github.com/antroids/application-title-bar/issues/10#issuecomment-1992015848 ... any plans?

**Comment by antroids** [comment]
> (except for the part that the "Keep Above" button does not get hided if we set the "**Show disabled elements**" to "_hide_" or "_hide, keep space_"... but for that i think i should fill another bug report...)

Should be resolved in 0.2.7

**Comment by savelmtr** [comment]
> > Any plans to provide a Global Menu alternative?
> Actually no. There is no way to use D-Bus from QML for now, and I don't want to add CPP plugins to the Widget.

Maybe we could use Nemo.DBus plugin as a requirement?
