### ISSUE TITLE
Add a setting to free up space on the panel if there are no active windows

### ISSUE THREAD

**Issue by Voron-Orel** [antroids/application-title-bar#11]
Add a setting to free up space on the panel if there are no active windows. 

![image](https://github.com/antroids/application-title-bar/assets/15307662/19e679db-3849-4a40-ab69-e4def7463546)
![image](https://github.com/antroids/application-title-bar/assets/15307662/12966e9b-1aa2-4fa1-965f-c6da9a982f03)

**Comment by Voron-Orel** [comment]
Thanks updated, but it works strangely. If you leave only the "title" out, it doesn't take up any space. If you leave the buttons, there is empty space.

<details>
  <summary>I use the following settings</summary>
  
![image](https://github.com/antroids/application-title-bar/assets/15307662/ee3516d3-f19a-4e77-8fe9-5dd6c75d16a0)

</details>

<details>
  <summary>It looks like this.</summary>
  
![image](https://github.com/antroids/application-title-bar/assets/15307662/6c30bd1c-85d9-4b49-a8f5-eabf49009076)

</details>

<details>
  <summary>If the window is not active the space occupied is minimal.</summary>
  
![image](https://github.com/antroids/application-title-bar/assets/15307662/04aba27f-6014-49ac-b9a8-d44052b6cac8)

</details>

<details>
  <summary>Same thing only with inactive buttons.</summary>
  
![image](https://github.com/antroids/application-title-bar/assets/15307662/f71b858b-ad8d-44f1-9419-39165df2e873)

</details>


Is it possible to fix this?

**Comment by antroids** [comment]
Could you check v0.2.8.
It seems that layout has undefined size without elements.
I added a small spacer that should keep space when all elements are hidden.
This also can be used in Edit mode.

**Comment by Voron-Orel** [comment]
Thanks Everything is working fine now.
