### ISSUE TITLE
Window Icon options

### ISSUE THREAD

**Issue by maverick74** [antroids/application-title-bar#12]
I don't know if this is possible to do and since it's a bit difficult to explain i'll try to give an example:

When we open Dolphin, in the window title bar, we get the software/app Icon.

If we left-click on the software icon we get a menu (the image is outdated but it looks something like this):

![imagem](https://github.com/antroids/application-title-bar/assets/14912461/1cfe89cc-894b-431a-b572-5dd5893d295e)

is it possible to open this same menu when we left-click the Window Icon on the plasmoid?

Would be great to have this options...

**Comment by antroids** [comment]
It's the Window Menu.
The similar has Task Manager plasmoid.
Need to implement it manually.

**Comment by maverick74** [comment]
> It's the Window Menu. The similar has Task Manager plasmoid. Need to implement it manually.

I'm going to be honest: I didn't notice the task manager had similar options!

Beside that, if you have to implement it **manually** I really don't think it's worth the work, specially now that you told me the task manager detail...

You can close this feature request if you want!

It just lost it's meaning to me!
