### ISSUE TITLE
[QUESTION] Act like panel space bar?

### ISSUE THREAD

**Issue by vanbwodonk** [antroids/application-title-bar#14]
Hi, thank you for making amazing this KDE plasmoid. 
Can this act like panel space bar? Already try it but failed. I need some space bar after global menu to drag or click app window.

**Comment by antroids** [comment]
Not sure what do you mean by space bar. 
Should it be a flexible empty space with configurable mouse events? 
In this case the widget cannot be flexible without title, because title is the only flexible element.

**Comment by vanbwodonk** [comment]
>  Should it be a flexible empty space with configurable mouse events?

Yes. it will be great if it can act this [plasmoid](https://github.com/luisbocanegra/plasma-panel-spacer-extended). Because title already can act with configurable mouse events.

**Comment by antroids** [comment]
I added an option to always show undefined title.
You can set the "Window title undefined" to blank and "Window title source" to always undefined to make the widget invisible. There are options to configure min/max size of the title element and "Fill free space on panel".

![Screenshot_Settings_always_undefined](https://github.com/antroids/application-title-bar/assets/36043354/b89c7d7f-4844-49f3-89cc-7d50712d493f)

**Comment by vanbwodonk** [comment]
Thank you. already tried it, but need to set correct minimum and maximum width. If it is not set properly, I noticed a gap between the system tray and the clock. But everything is working like charm now.
