### ISSUE TITLE
Aspect ratio of Breeze and Aurorae Window Control Buttons only in horizontal direction

### ISSUE THREAD

**Issue by Kasi07** [antroids/application-title-bar#17]
When selecting the Breeze or Aurorae icons theme the Buttons aspect ratio only changes the width but not the height.

Example at 50% ratio with Breeze Buttons:
![image](https://github.com/antroids/application-title-bar/assets/63197565/48a4c833-6dab-4996-abc0-4fbf65881534)

Also I noticed that the Aurorae buttons are very huge for me. I am not sure though if this is a bug with the theme or the plasmoid.
![image](https://github.com/antroids/application-title-bar/assets/63197565/68777f04-9a23-4f18-9396-c3ed9d93b948)

**Comment by antroids** [comment]
> When selecting the Breeze or Aurorae icons theme the Buttons aspect ratio only changes the width but not the height.

This is the second request about the Aspect ratio, but
> The aspect ratio of an image is the ratio of its width to its height

So, if you want wide buttons, you should set it >100.
Probably I need to add an info to this field too.

> Also I noticed that the Aurorae buttons are very huge for me. I am not sure though if this is a bug with the theme or the plasmoid.

It depends on an Aurorae theme. The Aurorae theme itself is not only the buttons, but frame and some additional information. The widget only uses icons, and ignores the rest.  Some of icons even have non-transparent background (e.g. catppuccin) and looks extremely ugly.
There are several options to configure layout:

1. Widget margins to add the space around whole widget.
2. Buttons spacing adds space between buttons.
3. Buttons margins adds spacing around each button.
4. You can also add spacer between buttons and following elements.

**Comment by Kasi07** [comment]
Okay, thanks for the explanation.
