### ISSUE TITLE
Show current aurorae themes

### ISSUE THREAD

**Issue by D3SOX** [antroids/application-title-bar#18]
![image](https://github.com/antroids/application-title-bar/assets/24937357/2839381c-fef1-44c1-87cf-949e6c6ccc0a)

I think it does not show CPP aurorae themes

![image](https://github.com/antroids/application-title-bar/assets/24937357/2d945cd6-24b6-43bd-8b5c-f2f8b88c1585)

**Comment by antroids** [comment]
Yup, you can hover "?" and read this 😁

**Comment by D3SOX** [comment]
Sorry I missed the "?". Is this something you might want to support in the future or not? It's definitely possible as the Window Buttons Applet does it.
Regarding your update 2: It is a fork of Breeze, I think that's normal

**Comment by antroids** [comment]
> Is this something you might want to support in the future or not? It's definitely possible as the Window Buttons Applet does it.

No, the Window Buttons Applet has a huge and complex [backend](https://github.com/psifidotos/applet-window-buttons/tree/master/libappletdecoration) library. This will add a lot of issues with compatibility and I don't think that it will be maintained well, especially during migration KDE to QT6.
The Application Title Bar has no CPP backend at all, it's pure QML.

**Comment by D3SOX** [comment]
Ok then I guess that's outside the scope of this project
