### ISSUE TITLE
App icon as a menu

### ISSUE THREAD

**Issue by mojtaba82** [antroids/application-title-bar#19]
In the titlebar of the windows, the application icon acts like a menu, and clicking on it opens a menu where you can perform actions such as fullscreen or moving the window to an activity or another desktop. can this be simulated for icon of application in your great widget?

**Comment by antroids** [comment]
I can add these actions to context menu, like this made for Task Manager widget.

**Comment by mojtaba82** [comment]
That'd be great

**Comment by antroids** [comment]
Context Menu options added in 0.4.1
