### ISSUE TITLE
Close unselected maximized window

### ISSUE THREAD

**Issue by maverick74** [antroids/application-title-bar#23]
Short story:
Is it possible to close an unselected, maximized (on the background) window?

Long Story:

I have a panel on top where i have the widget placed.

Widget Configurations:
    - **Show disabled elements:** Hide, keep Space
    - **Borderless Maximized Windows:** Enabled
    - **Disable for not Maximized:** Enabled

On the Desktop:
    - open two windows
    - Maximize one and leave the other not maximized (around the center of the screen).
    - Focus/select the one that is not maximized

Question: **how do i close the un-focused, maximized one directly without having to click on it (to focus it) and then close it?**

I don't know if there is any solution or if any of the following is possible, but...

Possible solutions:
    - have an option to show controls for the last maximized window focused
    - show controls for the last maximized window that mouse has hovered
    - ... others...

    
(i maybe missing some config...)

**Comment by antroids** [comment]
This is unsupported for now, but can be added as an option. All not maximized windows will be ignored by the widget in this case and with the "last active" option you will see last active maximized window.

**Comment by maverick74** [comment]
> This is unsupported for now, but can be added as an option.

Great :D

> you will see controls for last active maximized window.

This controls will show "faded" as the window is unfocused, right?

**Comment by maverick74** [comment]
OK by me! :)

**Comment by antroids** [comment]
Added option to Active task source drop down in version 0.4.4

**Comment by maverick74** [comment]
It's not working as expected!

1. It keeps commanding the selected window (either it is maximized or not), and not the window on the background
2. If i have a window maximized, and then i un-maximize it, i expected the widget to control the maximized window that is "behind" the now un-maximized (and selected/active) window

(if i'm being to confusing in the explanation, please say so :) )

**Comment by antroids** [comment]
I fixed another bug and cannot reproduce reported issue.
It seems you didn't use the new option, could you check.

![Screenshot_last_active_maximized](https://github.com/antroids/application-title-bar/assets/36043354/6096ca4d-f263-4b23-9fdb-e1bbb2ca4eab)

**Comment by maverick74** [comment]
No. I had it selected.

I'll remove and reinstall (like the last time i had problems and you could not replicate) to see if it's somekind of conflict between versions.

I'll report back in a few minutes...

**Comment by maverick74** [comment]
> I'll remove and reinstall

yeap!!! Nothing beats the biggest IT-Problem-Solver!!! 

And once again it solved it!!! :)

It's working just fine, now!

Thank You!

**Comment by maverick74** [comment]
Forgot to close...
