### ISSUE TITLE
Add option to only hide window control buttons and not title

### ISSUE THREAD

**Issue by nikcha** [antroids/application-title-bar#24]
I really like this widget and its customisability but it is not able to fully replicate the setup I had with applet-window-title and applet-window-buttons from psifidotos, namely having the option the hide the buttons but leaving the title as is. Being able to do this, or at least split the window buttons from window title would give a lot more functionality to the widget.

**Comment by antroids** [comment]
Could you please describe how this should work. 
This is the second request of the feature, but I cannot understand the use case.
And what it means "split"?

**Comment by maverick74** [comment]
@nikcha did the proposed solution worked for you? :)

**Comment by antroids** [comment]
> I really like this widget and its customisability but it is not able to fully replicate the setup I had with applet-window-title and applet-window-buttons from psifidotos, namely having the option the hide the buttons but leaving the title as is. Being able to do this, or at least split the window buttons from window title would give a lot more functionality to the widget.

Now it's possible to override elements set for maximized windows.
Added to 0.5.0

**Comment by maverick74** [comment]
> Now it's possible to override elements set for maximized windows. Added to 0.5.0

(kind of off topic: this not being able to be updated directly in the GHNS is driving me nuts! Every time there is a release I have to remove the old version, install the new one and then configure it all over again... @antroids do you know if there is any bug report about it?)

**Comment by antroids** [comment]
> > Now it's possible to override elements set for maximized windows. Added to 0.5.0
> 
> (kind of off topic: this not being able to be updated directly in the GHNS is driving me nuts! Every time there is a release I have to remove the old version, install the new one and then configure it all over again... @antroids do you know if there is any bug report about it?)

I added one-liners to the Readme file.

**Comment by maverick74** [comment]
Probably this is the related bug @antroids :
https://bugs.kde.org/show_bug.cgi?id=484057

**Comment by nikcha** [comment]
using two separate widgets simply configured as window action control and an active window title works perfectly. I will also try out that override feature that @antroids commited in #24 thank you
