### ISSUE TITLE
[Feature Request] Only show window buttons when focused window is maximized

### ISSUE THREAD

**Issue by rocka** [antroids/application-title-bar#26]
Can we have an option to only show window buttons when focused window is maximized, just like https://wiki.archlinux.org/title/KDE_package_guidelines#Plasma_widgets does?

Since normal windows already have their window buttons on the title bar, doing so can save some space in the panel.

**Comment by rocka** [comment]
There is a "Disable for not maximized" option under "Behavior" settings, but that option would disable window buttons and title entirely ...

**Comment by maverick74** [comment]
> There is a "Disable for not maximized" option under "Behavior" settings, but that option would disable window buttons and title entirely ...

Let me see if i understand you right...

You want to disable window buttons (close, restore, maximize), but want to keep Window title?

If that's the intention, then just use to different instances of the widget, each configured as you wish...
(e.g.: in one you set to show only the window buttons and set them to hide on maximize, on the other widget, you set only the window title and always visible)

**Comment by antroids** [comment]
I'm thinking about different sets of the elements for maximized and not maximized windows. I just need to figure out how to optimize this.

**Comment by maverick74** [comment]
> I'm thinking about different sets of the elements for maximized and not maximized windows. I just need to figure out how to optimize this.

Honestly, i think that will complicate the code (and the GUI) considerably when it can easily be worked around with the features already available within KDE...

but, naturally, that's up to you :)

**Comment by rocka** [comment]
> You want to disable window buttons (close, restore, maximize), but want to keep Window title (dup of #24 ?) ?

Yes, indeed, it's a duplicate, sorry for the inconvenient ... I would try to use 2 different instances for now.
