### ISSUE TITLE
[Feature Request] Window Icon size custom

### ISSUE THREAD

**Issue by kuolemax** [antroids/application-title-bar#28]
![image](https://github.com/antroids/application-title-bar/assets/25677528/6660e67c-48e9-48c1-9c85-7affb1a0b486)
the default window icon is too large, I wish it could be resized like text

**Comment by antroids** [comment]
Could you try to increase Widget Margins.

**Comment by kuolemax** [comment]
> Could you try to increase Widget Margins.

I set Widget Margins to 4 and it looks great。
![image](https://github.com/antroids/application-title-bar/assets/25677528/de7a85ac-d5c1-4a22-9493-4c1bec4ea7db)

thanks!
