### ISSUE TITLE
Window title not synced with active window

### ISSUE THREAD

**Issue by frasty** [antroids/application-title-bar#30]
Occasionally the widget's window title is not synced with the active window. Have to restart plasmashell to overcome this behavior. Using application-title-bar 0.5.1 on Wayland/Plasma 6.0.4

**Comment by antroids** [comment]
Does the context menu appear in the center of the screen?
I have the same issue after resume. 
It is a plasma or wayland issue.

What your GPU vendor?
Do you have multi-display setup?

**Comment by antroids** [comment]
Here is the bug report: https://bugs.kde.org/show_bug.cgi?id=482185

**Comment by frasty** [comment]
> Does the context menu appear in the center of the screen? I have the same issue after resume. It is a plasma or wayland issue.

Yes, it also happend to me that the window title starts to lose its synchronization with the active focused window after resume, but only occasionally. If I click on the widget with the right mouse button the context menu appears correctly and not in the center on the screen, so it seems another issue?

> 
> What your GPU vendor? Do you have multi-display setup?

It happens on both my workstations, both with single AMD GPUs, one on Wayland with a dual monitor setup and the other on X11 with a four monitor setup. Fyi I use separate screen focus with ActiveMouseScreen=false in kwinrc

**Comment by antroids** [comment]
Yes, it seems another issue.
Could you describe how the widget works when the issue appeared?
Is there the same problem with task manager widget?

**Comment by frasty** [comment]
I'll post an update when the issue will reappear as I already restarted plasmashell but iirc I don't remember to have noticed similar problems with Icon-only task manager

**Comment by antroids** [comment]
I'm not sure, but it seems like some applications can be associated with off-screen or already destroyed plasmashell instances or displays for some reason. I also noticed that some application can be closed when you are restarting the plasmashell.

**Comment by antroids** [comment]
It seems something was changed in Plasma 6.1.4 with Qt 6.7.2 or even before.
I cannot see the issues with detached context menu or unsyncronized TasksModel anymore.

**Comment by antroids** [comment]
I've got this issue several times in last couple days, however I still unable to reproduce the bug.
The Task Manager widget has correct data. 
It seems there is an inconsistency in the model and top row can be different from Active task at some moment even with single display.
I've added a timer, that will trigger a resync after 0.5 seconds after last Active task update as workaround.

**Comment by antroids** [comment]
LOL, I found the reason, and it's crazy!
![Screenshot_TasksModel_Debug](https://github.com/user-attachments/assets/5e36eb47-7110-4f81-9a6d-e7cf5e8a7bc5)
They use time only to store Last Activated and the items in the model are sorted incorrectly until you reactivate the task opened yesterday.

**Comment by frasty** [comment]
I just chime in to say that I am on 0.7.5 and still running in this bug after a few minutes of being logged in on PCs running Fedora 40 and Plasma 6.6.2/Qt 6.7.2.
I am used to have many Firefox windows (20-30) spread on two screens and two virtual desktops and that might be triggering the issue somewhat faster. No need to restart plasmashell. Oh, and I also make use of activities.
I just noticed that on desktops/screens with many windows opened it is more likely for the window title to be unsynched ot to not being updated at all.

**Comment by frasty** [comment]
After long testing I can confirm that window titles stop being synched after a few minutes when the number of open windows reaches a certain threshold. I have indeed ~180 Firefox open windows now and application title bar started to lose the synchronization with the active window in a few minutes after restoring the browser session. This doesn't happen if the number of open windows is lower than 15-20, maybe something more.

**Comment by antroids** [comment]
Thanks!
These steps to reproduce are really helpful.
I've split the issue into two: #67 and #68
