### ISSUE TITLE
Support for vertical bar

### ISSUE THREAD

**Issue by Mamiglia** [antroids/application-title-bar#35]
Hi, love what you're doing here! 

Would it be possible to add support for vertical sidebars? I believe there's many people interested in this possibility. 

Currently when using it on a vertical sidebar it shows only some cropped buttons on a horizontal line.
I would expect it to rather display the buttons from top to bottom.

![image](https://github.com/antroids/application-title-bar/assets/33762284/de34edfd-c12b-4dc1-8735-dff22633f98a)

Fedora 40, Plasma 6

**Comment by antroids** [comment]
It is possible to rotate the whole widget as-is, but I need to figure out to to manage widget size constraints, because they are not changing in this case.

**Comment by antroids** [comment]
Implemented in version 0.6.1

**Comment by Mamiglia** [comment]
Thanks, this is awesome!

![image](https://github.com/antroids/application-title-bar/assets/33762284/f22ed3a4-a2c4-4ea6-ac2e-79e9e53263ca)
![image](https://github.com/antroids/application-title-bar/assets/33762284/756906b6-37a5-4a63-9527-b462b79919e2)
