### ISSUE TITLE
Title Text Exceed The Widget and Get Behind Icon Only Task Manager

### ISSUE THREAD

**Issue by jingglang** [antroids/application-title-bar#39]
Thank you for this awesome plasmoid.

I enable the "Fill free space on panel" and set the Window Title maximum width with my horizontal resolution (1080px). Next to it is Icon Only Task Manager with "Fill free space" disabled. The problem is, when the app title is very long, it get behind of Icon Only Task Manager as seen in this picture:

![Screenshot_20240612_222937](https://github.com/antroids/application-title-bar/assets/3202382/e6202c1a-fabb-4b3d-94dc-b746f2b63d09)

Is there any solution to it?

**Comment by jingglang** [comment]
Version 0.5.2 doesn't have this problem.

**Comment by antroids** [comment]
Thank you for the report! 
Could you check the version 0.6.3.

**Comment by jingglang** [comment]
0.6.3 is good. Thank you.
