### ISSUE TITLE
Window controls and app title persist after closing all windows

### ISSUE THREAD

**Issue by Andrew-Mattias** [antroids/application-title-bar#4]
After closing all opened windows, **window controls** and **app title of last closed app** _persist_ (but there should be nothing because i set _undefined window title_ field to epty). It is easily reproducible on my machine on plasma 6.0.0. by quickly opening and closing a bunch of apps.

**Comment by antroids** [comment]
Thank you for the report!
This should be fixed in [version 0.2.2](https://github.com/antroids/application-title-bar/releases/tag/v0.2.2).

**Comment by Andrew-Mattias** [comment]
> Thank you for the report! This should be fixed in [version 0.2.2](https://github.com/antroids/application-title-bar/releases/tag/v0.2.2).

This is cool! When should we expect v0.2.2 to be pushed into plasma store? It is v0.1 currently shipped.

**Comment by antroids** [comment]
I think today, tomorrow at the latest.

**Comment by antroids** [comment]
Release uploaded to the store.
