### ISSUE TITLE
Window titles are not being replaced when using Plasma scripting to configure widget title replacements

### ISSUE THREAD

**Issue by HeitorAugustoLN** [antroids/application-title-bar#45]
I am encountering an issue where title replacements are not being set when configuring the widget using Plasma scripting. The title replacements work correctly when set through the widget's configuration interface, but not when applied through a script. Settings

#### Expected behavior:

The title replacements should be set correctly when the widget is configured via the script.

#### Actual Behavior:
The title replacements are not set when the widget is configured using the script, even though the same configuration works when set through the widget's configuration interface.

#### Additional Information:

- Plasma version: 6.1.2
- Application-title-bar version: 0.6.6

Script being used (it is longer, but I think this is the only part that matters):

![image](https://github.com/antroids/application-title-bar/assets/44377258/e8dbf0f8-7972-4853-9eaa-7e57623d89f0)

Replacements tab after the script being run:

![image](https://github.com/antroids/application-title-bar/assets/44377258/5d21f2fc-b0c5-4687-b50e-8c3856541704)

Window title example:

![image](https://github.com/antroids/application-title-bar/assets/44377258/1c93a061-04f7-4126-8b5f-b77c8655bf20)

**Comment by antroids** [comment]
Have you tried to restart the plasmashell after the script applied? 
Probably change event not sent or not handled properly for the list field.

**Comment by HeitorAugustoLN** [comment]
> Have you tried to restart the plasmashell after the script applied? Probably change event not sent or not handled properly for the list field.

No, I haven't. Now that I restarted, it is now replaced the titles.

**Comment by antroids** [comment]
> > Have you tried to restart the plasmashell after the script applied? Probably change event not sent or not handled properly for the list field.
> 
> No, I haven't. Now that I restarted, it replaced the titles.

It seems the plasmashell is not reloading configuration on file changes. You have to restart it or call reloadConfig from the widget itself.
