### ISSUE TITLE
Missing MAC OS theme

### ISSUE THREAD

**Issue by Eng-Zakaria** [antroids/application-title-bar#47]
Please add at least one mac theme may be something like macSonoma dark or any mac theme would be great ;)
Thank you for your effort :D

**Comment by antroids** [comment]
Could you try this one: https://github.com/vinceliuice/MacSonoma-kde
You need to install the theme, change "Button icons source" to "Aurorae" and select the theme from the "Aurorae theme" dropdown.

**Comment by Eng-Zakaria** [comment]
works just as expected great job, your extension is what keeps me in KDE
