### ISSUE TITLE
[Question/Proposal] List installed cpp-compiled window decorations themes

### ISSUE THREAD

**Issue by Andrew-Mattias** [antroids/application-title-bar#48]
Inspired by https://github.com/antroids/application-title-bar/issues/18

Is it possible to simply _list_ unsupported cpp window decoration themes (e.g. Plastik and Klassy) in Aurorae ComboBox with "(cpp/not-supported)" prefix?

User would know that widget is _aware_ of installed themes, even if it cant use them, preventing confusion.
Simple listing existing themes should be doable easily enough.

![313773129-2839381c-fef1-44c1-87cf-949e6c6ccc0a](https://github.com/user-attachments/assets/3dcde762-5f0e-4ca9-a019-ce3615a78532)

![313773197-2d945cd6-24b6-43bd-8b5c-f2f8b88c1585](https://github.com/user-attachments/assets/948305b5-cc5b-457f-9ea3-4a26ba06ff8d)

**Comment by antroids** [comment]
It seems no, there is nothing I can do in QML with that.
Kpackagetool6 shows only locally installed themes, perhaps Aurorae only.
[Decorationmodel](https://github.com/KDE/kwin/blob/master/src/kcms/decoration/decorationmodel.h) is used by [KWin KCM](https://github.com/KDE/kwin/blob/master/src/kcms/decoration/kcm.cpp) only, that is not exposed as QML module.

**Comment by Andrew-Mattias** [comment]
If i understood you correctly;

1. To implement this feature writing plugin is a must?

2. It is not really feasible to make a plugin that use KWin KCM's method of theme detection due to possible future instability of said implementation as codebase moves / technical difficulty of implementation of such a plugin?

3. There are no forseeable reliable methods to detect binary themes other that KWin KCM one?

**Comment by antroids** [comment]
At least a plugin is required, I didn't check further.

**Comment by Andrew-Mattias** [comment]
ok, since proposal is non-trivial to implement and i am not able to implement it myself, i think i should close this issue for the time being.

**Comment by linuxtopia** [comment]
> It seems no, there is nothing I can do in QML with that. Kpackagetool6 shows only locally installed themes, perhaps Aurorae only. [Decorationmodel](https://github.com/KDE/kwin/blob/master/src/kcms/decoration/decorationmodel.h) is used by [KWin KCM](https://github.com/KDE/kwin/blob/master/src/kcms/decoration/kcm.cpp) only, that is not exposed as QML module.

plastik is also the one from default, why we cannot see in icon set of the widget?

![Image](https://github.com/user-attachments/assets/84a3283d-aba9-4c2f-a588-f7ddd051e73e)
