### ISSUE TITLE
Library import version errors in Application Title Bar plasmoid on Debian 12 with KDE

### ISSUE THREAD

**Issue by fengyuanluo** [antroids/application-title-bar#49]
## Description

When using the Application Title Bar plasmoid on Debian 12 with KDE environment, multiple errors are encountered related to library import versions.How can I fix it?

## Environment
- Operating System: Debian 12
- Desktop Environment: KDE
- Plasmoid: Application Title Bar 0.7.0 (com.github.antroids.application-title-bar)

## Error Messages

The following errors are displayed:

1. file:///usr/share/plasma/plasmoids/com.github.antroids.application-title-bar/contents/ui/main.qml: Library import requires a version

2. file:///usr/share/plasma/plasmoids/com.github.antroids.application-title-bar/contents/ui/main.qml:9:28: Library import requires a version

3. file:///usr/share/plasma/plasmoids/com.github.antroids.application-title-bar/contents/ui/main.qml:10:37: Library import requires a version

4. file:///usr/share/plasma/plasmoids/com.github.antroids.application-title-bar/contents/ui/main.qml:11:31: Library import requires a version

5. file:///usr/share/plasma/plasmoids/com.github.antroids.application-title-bar/contents/ui/main.qml:12:33: Library import requires a version

6. file:///usr/share/plasma/plasmoids/com.github.antroids.application-title-bar/contents/ui/main.qml:14:31: Library import requires a version

**Comment by antroids** [comment]
The widget is created for Plasma 6 with Qt6, I don't think you have it on a stable debian. Try some other old widgets, created for Plasma 5.

**Comment by fengyuanluo** [comment]
OMG this is terrible, thanks for your reply

**Comment by fengyuanluo** [comment]
I finally used Active Window Control plasmoid to successfully achieve my needs
