### ISSUE TITLE
(Feature request): App icon display before window title

### ISSUE THREAD

**Issue by Andrew-Mattias** [antroids/application-title-bar#5]
In Active window control widget from plasma 5 there was an option to display app icon. It would be extra nice to have this option in this plasmoid as well. Rationale:

App icon option was indescribably cool, because you could visually detect focused app by icon (which is much more compact then application name and much more readable then cut down application name) and simultaneously have window title with opened file/page name (text) in order to not get confused if you opened a lot of files/pages with same app (e.g. many different dolphin windows with different folders or many GIMP windows with different pictures). 

It should be optimal to use colored icons variants as default since many icon themes does not have symbolic versions of icons for most apps.

App icon addition will make this widget feature-complete (aside from window decorations theming support, which is just a matter of slight visual polish).

**Comment by antroids** [comment]
Yup, could you check the release 0.2.1 in the [Store](https://www.pling.com/p/2135509).
I added Icon and drag&drop elements editor.

![Screenshot_0 2 2](https://github.com/antroids/application-title-bar/assets/36043354/d03d4d7b-9de0-44a6-8f7a-15d0e85226dd)

**Comment by antroids** [comment]
Added in 0.2.1
