### ISSUE TITLE
Some applications when using `Application Name` as the source are being cut out from Window Title

### ISSUE THREAD

**Issue by HeitorAugustoLN** [antroids/application-title-bar#50]
I am using version 0.7.0 in NixOS. And this is happening:

Kate:
![image](https://github.com/user-attachments/assets/d934c46f-ef54-41c9-9c86-cbef8eb38076)

Widget settings:

![image](https://github.com/user-attachments/assets/8b726f20-60a4-46bf-9898-fff8e0e17f60)

This were the only ones I noticed, other applications work fine, such as Firefox, Spotify, Dolphin, etc.

**Comment by antroids** [comment]
It seems the difference between the applications in menu width.
Is there widget in the space to the right of Global Menu?
Without "Fill free space" option the widget doesn't tell to the panel layout how much space it prefers and the space can be filled by others greedy widgets.

**Comment by HeitorAugustoLN** [comment]
> Is there widget in the space to the right of Global Menu?

No, only panel spacer.

> Without "Fill free space" option the widget doesn't tell to the panel layout how much space it prefers and the space can be filled by others greedy widgets.

Enabling fill free space didn't fix the issue.

**Comment by HeitorAugustoLN** [comment]
I found out that v0.6.8 don't have this issue. Which was the previous version I was using before updating.

**Comment by HeitorAugustoLN** [comment]
Tested with v0.6.9, it has the issue.

**Comment by antroids** [comment]
> Tested with v0.6.9, it has the issue.

Great, thanks, I'll take a look.

**Comment by antroids** [comment]
Could you Export widget Configuration via context menu and attach.
I still unable to reproduce the bug.
And what is your Qt version?

**Comment by HeitorAugustoLN** [comment]
[application-title-bar.txt](https://github.com/user-attachments/files/16679658/application-title-bar.txt)

Changed file extension to `.txt` because github doesn't let me attach a `.cfg`

My Qt version is 6.7.2

**Comment by antroids** [comment]
Oh, I have reproduced the issue.
Something wrong with title width calculation when the font is not bold.

**Comment by antroids** [comment]
Could you test the 0.7.1

**Comment by HeitorAugustoLN** [comment]
Tested it. It works fine now.

![image](https://github.com/user-attachments/assets/4b7e5339-03ca-433b-83a0-745e553e5d9c)
