### ISSUE TITLE
(Feature proposal): Window controls icons taken from current window decoration theme

### ISSUE THREAD

**Issue by Andrew-Mattias** [antroids/application-title-bar#6]
Current default window controls icons (close,minimize,maximize) are cool, but it would be even cooler if they could be optionally set to match current window decoration theme. I use default breeze and my brain itches every time i use this wonderful widget because of non-breeze icons. This is not crucial, but would be very welcomed.

UPD 1: I use cutom icon theme (tela-icon theme). Maybe my window controls icons in widget match icon theme and not window decoration theme?

UPD 2: Here how it looks on my machine. On your screenshots window controls icons were breeze everywhere. A bug maybe?
![изображение](https://github.com/antroids/application-title-bar/assets/91881068/5e2021d2-94c4-455b-bd3a-98051529f3cd)

UPD 3: Issue of non-matching widget and window decoration WC incons is persistent in both 0.1 and 0.2.3 versions of widget.

UPD 4: I spinned up fresh WM with KDE neon (same as my system where bug was detected) and figured that widget load window control icons from icon theme (not from window decorations theme, which makes sense for every other type of widget exept yours)! I set icon theme to tela-icons theme, installed v2.3 of widget and reproduced issue from UPD 1. To fix non-breeze icons in widget i have to set icon theme to breeze and reboot.
![изображение](https://github.com/antroids/application-title-bar/assets/91881068/ac903250-209f-45e0-9adb-377c59eb8566)
So, at the end, Window controls icons taken from current window decoration theme would be a great cherry on top of good widget (off-topic: i use your widget on my production machine and i cant be more happy with how fast and robust it is, kudos for great work)

UPD 5: window decorations theme spin of breeze is much cooler than icon theme spin of breeze, because its base shows on mouse hover:

**no hover**
![Снимок экрана_20240309_013253](https://github.com/antroids/application-title-bar/assets/91881068/0bd19654-f59d-4794-898b-25f42bfea8f6)

**hover**
![Снимок экрана_20240309_013426](https://github.com/antroids/application-title-bar/assets/91881068/20cd2b20-a10b-4acd-a3c1-9ce9f4498d14)
![Снимок экрана_20240309_013515](https://github.com/antroids/application-title-bar/assets/91881068/0c205239-04e8-41eb-9bd1-d88fd42353ba)

Hope that icons in widget would behave like in the latter example.

**Comment by antroids** [comment]
Added a theme support to 0.2.6, that is uploaded to the Store.
Could you please check.

The Breeze theme implemented as binary library. Not sure that we can use icons from it. 
Probably some Aurorae Breeze theme can be used instead.

**Comment by antroids** [comment]
I ported Breeze icons implementation into QML.
Added into Release 0.3.3.

**Comment by Andrew-Mattias** [comment]
Did i understand you correctly: You added option to use breeze icons by manually hardcoding them into widget? 

If so and if it looks identical to icons from UPD 5, its probably okay for me (since i don't plan to use other themes), but i was talking about option to load icons from window decoration theme (a.k.a aurorae theme). Do you plan to add general aurorae themes support?

I imagined it to be separate section inside "Appearance" page named "Button icons theming" with 3 options: 
"icons from icon theme" <== default in v2.3 of widget
"icons from aurorae (window decorations) theme" <== proposed feature
"Breeze" <== hardcoded option of yours (if i undestand you correctly)

**Comment by antroids** [comment]
> Did i understand you correctly: You added option to use breeze icons by manually hardcoding them into widget?

Yes. The Breeze icons are hardcoded into KDE decoration library, they are not just icons files. Their colors depends on Kirigami. I implemented the same icons in the widget, the only difference is that they will have color theme from the panel, not from window title.

Now there are 3 options for icons theming:
1. Plasma: based on theme icons.
2. Breeze: new option.
3. Aurorae: icons from Aurorae theme, can be chosen in combo box.

**Comment by Andrew-Mattias** [comment]
>     3. Aurorae: icons from Aurorae theme, can be chosen in combo box.

I am going to test this option in a kde neon WM in a couple of minutes,

**Comment by antroids** [comment]
Thank you for the response!

> 1. Hope that aurorae themes installed by default recognition could be fixed.

No, the booth Breeze and Plastic are implemented as binary libraries and they unfortunately are not supported as Aurorae themes by the widget.

> 2. Buttons aspect ratio customization is a bit broken - it squeezes button icons horizontally but not vertically. It seems that issue persists with any aurorae theme

Aspect ratio is width:height ratio, it works as intended. When the value is less than 100, squeezes horizontally, otherwise vertically. Height is not changing by this parameter. I think you want the Window Margins option. Probably separated button margins option could be helpful too.

> 3. In v3.3 of widget you must manually choose aurorae theme. It would be nice if in aurorae theme combo box there was an option <Current system Aurorae theme> which pulls icons for widget from current system Aurorae theme (chosen to be used in system settings) for you. It also should default logically. Can it be implemented?

I cannot see a clean way how to do it.

**Comment by Andrew-Mattias** [comment]
> No, the booth Breeze and Plastic are implemented as binary libraries and they unfortunately are not supported as Aurorae themes by the widget.

That is unfortunate. : ( 

> I think you want the Window Margins option. Probably separated button margins option could be helpful too.

Yes!  Window margins do the trick for resizing buttons, but app icon shrinks too, which is not desired.
![изображение](https://github.com/antroids/application-title-bar/assets/91881068/3336248f-adc1-4a70-a4ec-3120fa6b9f7a)
separated button margins (buttons resize) and icon margins (app icon resize) would be nice.

> I cannot see a clean way how to do it.

That is sad. : ( But situation still can be improved. 
- If Widget cant detect any aurorae themes, combo box should not be empty, it should contain text <no aurorae themes detected\> and should not be active. It is much less obscure than current emty'ish drop-list and more clear.
- If widget can detect aurorae theme it should contain text <сhoose aurorae theme\> and should be active. It makes need to manually choose aurorae theme more obvious and clear.
- there should be some sort of info button (with "i" or "?" emblem or smth similar) next to combo box, which displays tool-tip with explanation on hover/click:
"Some window decoration themes, e.g. Breeze or else, could be installed in your system as binary libraries and thus be visible in system settings, but they are not detectable and cannot be used by this widget (unlike auraroe themes). Proceed to install some aurorae themes or use "Breeze" or "Plasma" options in "icons theme" field instead".

**Comment by antroids** [comment]
1. Button margins option added.
2. Added tips and messages for empty Aurorae theme ComboBox.

**Comment by Andrew-Mattias** [comment]
i will test it today or tomorrow to se if there any hiccups left (to be sure that feature is compleete). Kudos for great work!

**Comment by Andrew-Mattias** [comment]
Its almost perfect. There are some visual nitpicks, which could be resolved. They are tiny, but they scratch brain and eyes.

I. In "window control buttons" section:

1. Rename "Icons theme" to "Button icons source", which is more comprehensible, straightforward and less confusing (usually "icons theme" is a reference to Application icons theme, but not here) 

2. Remove first [?] info button and rename ComboBox options as follows:
_Plasma_ => Plasma: Global icon theme
_Breeze_ => Breeze: Implicit Breeze icons
_Aurorae_ => Aurorae: Window decorations theme

There are plenty room inside ComboBox to write full clarification of icons source, and in combination with renaming from pt.1 above, first [?] info button is no longer needed.

![1 2](https://github.com/antroids/application-title-bar/assets/91881068/482ac65c-0dd4-4eff-92bf-b37bf87c9f19)

3. Replace second [?] info button with [!] info button. Information inside tooltip of second [?] info button is not "want know more?" type and more of "warning, limitations!" type, so [!] sign is more appropriate and should grab more attention during first use (which should decrease misunderstanding of feature limitations)

4. Pin left border of Tooltip to the left border of ComboBox and Pin right border of Tooltip to the right border of second info button. Current tooltip borders are out of place and are not pretty.

![изображение](https://github.com/antroids/application-title-bar/assets/91881068/36fc813d-c7b2-46da-b302-7b462a6e0156)

5. If Aurorae option is selected, but no themes are found, ComboBox is still clickable and gives empty list on click. ComboBox should be deactivated if no Aurorae themes are found, even if Aurorae option is selected.

![изображение](https://github.com/antroids/application-title-bar/assets/91881068/9cdc36bd-8c10-4b76-940a-64895edd584b)

6. Text inside Aurarae theme info button should be come in two variants:

**If Aurorae themes are not found, tooltip text should be as follows:**

_"Some window decorations themes, e.g. Breeze or Plastik, could be installed in your system as binary libraries and thus be visible and usable in System settings, but they are not detectable and cannot be used by this widget. There are no plans to support such binary themes due to technical complications._
\-
_Regular Aurorae themes for window decorations are supported by this widget and you can install them in System settings through "Window decorations" page or use "Breeze" or "Plasma" options in "icons theme" field above instead"_

**If some Aurorae themes are found, tooltip text should be as follows:**

_"Some window decorations themes, e.g. Breeze or Plastik, could be installed in your system as binary libraries and thus be visible and usable in System settings, but they are not detectable and cannot be used by this widget. There are no plans to support such binary themes due to technical complications._
\-
_You can install more of regular Aurorae themes for window decorations in System settings through "Window decorations" page or use "Breeze" or "Plasma" options in "icons theme" field above instead"_

![изображение](https://github.com/antroids/application-title-bar/assets/91881068/2de25f0e-c721-4d56-a275-c6fa3243ca86)

7. Rename "Buttons aspect ration %:" to "Correct buttons width/height ratio %:", which is more straightforward and less confusing (new variant field name tells user exactly what it is doing unlike current variant).

8. Pin left border of Tooltip to the left border of ComboBox and Pin right border of Tooltip to the right border of second info button. Current tooltip borders are out of place and are not pretty.

9. Due to renaming from pt.7 it is only logical to remove first sentence from tooltip.

![изображение](https://github.com/antroids/application-title-bar/assets/91881068/f039c1b8-5129-4a5a-8d13-618b32ce8fac)

10. Pin left border of Tooltip to the left border of ComboBox and Pin right border of Tooltip to the right border of second info button. Current tooltip borders are out of place and are not pretty.

![изображение](https://github.com/antroids/application-title-bar/assets/91881068/57c778f6-cb9d-4a70-9f07-dafa2f9b4815)


Most of these issues are minor nitpicks, but every fix will brings some UX improvements and make widget more polished overall. I think that after dealing with above mentioned issues Window control icons customization will be complete and this Github issue could be close. Thanks for your work!

**Comment by Andrew-Mattias** [comment]
BTW, i have an off-topic question: Could you make Plasma 6 reincarnation of "Compact Shutdown" widget ([link](https://store.kde.org/p/1483671/))? Default "Log/Logout" widget is meh, because it is not as snappy and you cannot avoid blurred full-screen Plasma shutdown options menu.

**Comment by antroids** [comment]
> BTW, i have an off-topic question: Could you make Plasma 6 reincarnation of "Compact Shutdown" widget ([link](https://store.kde.org/p/1483671/))? Default "Log/Logout" widget is meh, because it is not as snappy and you cannot avoid blurred full-screen Plasma shutdown options menu. An ability to reliably and quickly Shutdown/Reboot/End Session/Lock/Change User/Sleep/Hibernate your machine in two swift clicks was Godsent. Plasma 6 re-implementation should be fairly easy (compared to application-title-bar widget), and should not require much maintenance after being done.

You could check [Quick Shutdown](https://store.kde.org/p/2138152/), looks like it is under active development now.

**Comment by Andrew-Mattias** [comment]
> You could check [Quick Shutdown](https://store.kde.org/p/2138152/), looks like it is under active development now.

Thanks for the hint! This widget is functionally sufficient, but its nonadjustable default appearance leaves lot to be desired. Thanks for help nevertheless.

**Comment by antroids** [comment]
Thank you for the suggestions!
Unfortunately the ContextualHelpButton component cannot be customized in that way.
The icon is "help-contextual" and it depends on theme:
![image](https://github.com/antroids/application-title-bar/assets/36043354/63918eab-2509-4866-b644-b69570393cac)

I added suggestions 1, 2, 5, 6, 7 into version 0.4.3

**Comment by Andrew-Mattias** [comment]
Window control buttons theming is now complete (cant imagine how to improve this aspect of a widget further).
I think it is logical to close this feature request as complete.

**Comment by antroids** [comment]
> Hi,
> 
> I'm using the `Plasma: Global icon theme` option, with the default Breeze Dark theme, which mostly work fine, except :
> 
> * regardless of how I play with `Wiget margins` and `Buttons width/height ratio`, I can't get these buttons to the same size as default Plasma's window decoration buttons size ;
> * I can't find out how to make the close white instead of red when not hovered, also like default Plasma's window decoration buttons behave.
> 
> Thanks

You can switch to "Breeze: Implicit Breeze icons" option to get Breeze icons. 
However, colors can be different because window decorations and panels are using different themes.

**Comment by KaKi87** [comment]
That works, thanks !

So, to make the panel buttons have the same size as the decorations buttons, I set `Wiget margins` to `5` and `Buttons width/height ratio` back to the default `100`.

Thanks
