### ISSUE TITLE
Can not remove elemens on the Widget Layout menu

### ISSUE THREAD

**Issue by MrFacundo** [antroids/application-title-bar#61]
Hi! When clicking on the remove button, nothing happens.

![image](https://github.com/user-attachments/assets/8f51a8db-23e1-4bb6-8a55-fb2b46ee4ebf)

Environment

    KWin version: 6.2.0
    Distro: [Archlinux]
    Plugin version: 0.7.4

**Comment by antroids** [comment]
It's not a button, it's a drop area.
You can drag any element from the "Elements" field too remove it.

**Comment by MrFacundo** [comment]
Oh I see, I never thought of doing that!
