### ISSUE TITLE
Add an application blacklist

### ISSUE THREAD

**Issue by ElHyperion** [antroids/application-title-bar#62]
It would be nice to be able to disable this widget for certain applications that draw their own title bar buttons, such as Firefox. I use this widget only for displaying titlebar buttons for maximised apps (as I hide their native title bar when they are maximised), but this results in having two sets of window title buttons in some applications:

![image](https://github.com/user-attachments/assets/8c437841-2d35-4c50-abd9-bbdb76c8cde9)

**Comment by antroids** [comment]
I don't think that it's a good idea to have window controls in different places for different applications.
If you mostly use maximised browser windows, you can enable native title bars for them. These additional control will be removed.

![Screenshot_20241028_131025](https://github.com/user-attachments/assets/c4701c1e-97ad-4d17-ac79-4d1b01f063d3)

**Comment by ElHyperion** [comment]
Yup, I would also hate to have these controls in different places, I only thought it would be better to have one set of controls albeit in a different place than having two controls above each other.

I didn't know it can be fixed by showing the native title bar, thanks for the tip! I would prefer to preserve the custom one for un-maximised windows, but I'll rather keep the option checked as I usually have my browser maximised anyways.

I suppose this can be closed then if there isn't any other use case for this and it's not in-line with your design preferences.
