### ISSUE TITLE
Widget is not showing anything when portal dialog window is in focus

### ISSUE THREAD

**Issue by Andrew-Mattias** [antroids/application-title-bar#7]
After I tried to *open file with* in Telegram desktop, the portal to choose the app to open said file appeared. The widget became empty (I configured *window title undefined* to empty) after the portal dialog window came into focus, as if the portal dialog window were not a window. Is it intended behavior? Could it be fixed? It would be super nice to make widget treat portal dialog windows same as regular windows, because muscle memory trained to close any focused window by clicking top left corner stumbles when suddenly closing focused window with a widget is no longer an option.

![изображение](https://github.com/antroids/application-title-bar/assets/91881068/2d81a983-48bd-4e4c-ab3b-f15125b7ed3f)

**Comment by antroids** [comment]
Yeah, reproduced on Google Chrome and Telegram. The portal task icon blinks and then disappears from Task Manager. 
This is a Plasma framework bug, I filled the report.
It's interesting that Firefox and Chromium works well, probably wayland issue.

**Comment by antroids** [comment]
This is resolved in KDE Frameworks 6.1 with Chrome 124.0.6367.60.
However, it is still not fixed in Telegram.

> It's an issue on Wayland with the dialog not being marked as a dialog correctly. Now that the xdg-dialog-v1 Wayland protocol has been merged (see https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/228) it's up to Chromium to support it so that this can work as expected.
