### ISSUE TITLE
(Feature Request) Fill Free Space on Panel

### ISSUE THREAD

**Issue by jingglang** [antroids/application-title-bar#9]
Thank you for this great plasmoid.

Could you please add "Fill Free Space on Panel" similar with the one in "Icon-only Task Manager".

Thank you

**Comment by antroids** [comment]
Added to 0.2.7.
Incompatible with flexible spacers for now, but looks like with flexible "Icon-only Task Manager" works well.

**Comment by jingglang** [comment]
Great. Works well.
Thank you.
![Screenshot_20240316_232614](https://github.com/antroids/application-title-bar/assets/3202382/33308292-c73e-46b6-8580-3391102bdbeb)
